---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: silverbullet
spec:
  parentRefs: [{ name: traefik-gateway, namespace: traefik }]
  hostnames: [documente.mon.enorme.uk]
  rules:
    - filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: auth-via-authelia
      backendRefs:
       - name: silverbullet
         port: 3000

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-via-authelia
spec:
  forwardAuth:
    address: http://authelia.auth.svc.cluster.local:9091/api/authz/forward-auth
    authSigninURL: https://identifie.mon.enorme.uk
    trustForwardHeader: true
    maxResponseBodySize: 8192
    authResponseHeaders: [Remote-User, Remote-Groups, Remote-Email, Remote-Name]
