---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: minecraft
  ports:
  - name: minecraft
    protocol: TCP
    port: 25565
    targetPort: minecraft
    nodePort: 30566
  - name: minecraft-query
    protocol: UDP
    port: 25565
    targetPort: minecraft-query
    nodePort: 30566
