---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: kanidm
    includeTemplates: true
    includeSelectors: true
  - pairs:
      app.kubernetes.io/component: kanidm
    includeTemplates: true

namespace: auth
resources:
  - deployment.yml
  - pv.yml
  - service.yml
  - cert-identifie-mon-enorme-uk.yml
