---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie
spec:
  ingressClassName: nginx
  rules:
  - host: mange.mon.enorme.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: { name: mealie, port: { name: http } }
  tls:
  # use default certificate
  - hosts:
    - '*.mon.enorme.uk'

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mealie
spec:
  parentRefs: [{ name: traefik-gateway, namespace: traefik }]
  hostnames: [mange.mon.enorme.uk]
  rules:
    - backendRefs:
       - name: mealie
         port: 9000
