---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-gtnh
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy: { type: Recreate }

  template:
    spec:
      containers:
        - name: minecraft
          image: minecraft-gtnh
          env:
            - { name: TZ, value: Europe/Paris }
            - { name: UID, value: '1000' }
            - { name: GID, value: '1000' }

            - { name: TYPE, value: GTNH }
            - { name: EULA, value: 'true' }
            - { name: INIT_MEMORY, value: 4G }
            - { name: MAX_MEMORY, value: 10G }
            - { name: ENABLE_AUTOPAUSE, value: 'true' }
            - { name: AUTOPAUSE_TIMEOUT_EST, value: '1200' } # 20min = 1 minecraft day
            - { name: AUTOPAUSE_TIMEOUT_INIT, value: '600' }
            - { name: ENABLE_QUERY, value: 'true' }

            - { name: GTNH_PACK_VERSION, value: '2.9.0-RC-1' }
            # Additionnal mods
            - name: MODS
              value: |
                https://github.com/GTNewHorizons/ServerUtilities/releases/download/2.4.13/ServerUtilities-2.4.13.jar
                https://github.com/FalsePattern/LagGogglesLegacy/releases/download/4.17.0/laggoggles-mc1.7.10-4.17.0.jar

            - { name: VIEW_DISTANCE, value: '32' }
            - { name: MAX_TICK_TIME, value: '-1' }
            - { name: ENABLE_WHITELIST, value: 'true' }
            - { name: WHITELIST, value: 'istoleyurballs' }
            - { name: OPS, value: 'istoleyurballs' }

            - { name: MOTD, value: '-==XXX==- NO GIRLS ALLOWED -==XXX==-' }
            - { name: ICON, value: /config/server-icon.png }
            - { name: OVERRIDE_ICON, value: 'true' }
            - { name: MODE, value: survival }
            - { name: SEED, value: balls }

            # For the first time, uncomment this value, make the config changes, and comment this line again.
            # Config changes are: disable game of light (config/lootgames/game_of_light.cfg, weight), disable underground dirt/gravel (config/GregTech/WorldGeneration.cfg).
            # - { name: SETUP_ONLY, value: 'true' }
          ports:
            - { name: minecraft, containerPort: 25565 }
          volumeMounts:
            - { name: config, mountPath: /config/server-icon.png, subPath: server-icon.png, readOnly: true }
            - { name: data, mountPath: /data }
            - { name: backups, mountPath: /data/backups }
          resources:
            requests: { cpu: 1000m, memory: 4Gi }
            limits: { cpu: 7000m, memory: 11Gi }

      volumes:
        - { name: config, configMap: { name: minecraft-gtnh-cm } }
        - { name: data, persistentVolumeClaim: { claimName: minecraft-gtnh-data-pvc } }
        - { name: backups, persistentVolumeClaim: { claimName: minecraft-gtnh-backups-pvc } }
