---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-gtnh-data-pv
spec:
  local:
    path: /mnt/fastfs/apps/minecraft-gtnh/data
  capacity: { storage: 20Gi }
  accessModes: [ReadWriteOncePod]
  storageClassName: ''
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions: [{ key: kubernetes.io/hostname, operator: In, values: [coruscant] }]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-gtnh-data-pvc
spec:
  volumeName: minecraft-gtnh-data-pv
  storageClassName: ''
  accessModes: [ReadWriteOncePod]
  resources: { requests: { storage: 20Gi } }

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-gtnh-backups-pv
spec:
  local:
    path: /mnt/lucastrunk/@apps/@minecraft-gtnh/backups
  capacity: { storage: 100Gi }
  accessModes: [ReadWriteOncePod]
  storageClassName: ''
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions: [{ key: kubernetes.io/hostname, operator: In, values: [coruscant] }]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-gtnh-backups-pvc
spec:
  volumeName: minecraft-gtnh-backups-pv
  storageClassName: ''
  accessModes: [ReadWriteOncePod]
  resources: { requests: { storage: 100Gi } }
