---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: vaultwarden
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true

namespace: vaultwarden
resources:
  - namespace.yml
  - vaultwarden
  - networking.yml

images:
  - name: vaultwarden
    newName: ghcr.io/dani-garcia/vaultwarden
    newTag: 1.35.7-alpine
