---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: forgejo
    includeTemplates: true
    includeSelectors: true
  - pairs:
      app.kubernetes.io/part-of: forgejo
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true

namespace: forgejo
resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - ingress.yml
  - pv.yml

images:
  - name: forgejo
    newName: codeberg.org/forgejo/forgejo
    newTag: 15.0.1
