---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: nvidia-device-plugin
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true

namespace: nvidia-device-plugin
resources:
  - namespace.yml
  - https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/refs/tags/v0.19.2/deployments/static/nvidia-device-plugin.yml
patches:
  - path: restrict-ilum.yml
