---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data-pv
spec:
  local:
    path: /mnt/rootfs/@apps/@prometheus/data
  capacity: { storage: 11G }
  accessModes: [ReadWriteOncePod]
  storageClassName: ''
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [coruscant]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-pvc
spec:
  volumeName: prometheus-data-pv
  storageClassName: ''
  accessModes: [ReadWriteOncePod]
  resources: { requests: { storage: 11G } }
