---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy: { type: Recreate }

  template:
    spec:
      containers:
        - name: jellyfin
          image: jellyfin
          env:
            - { name: TZ, value: Europe/Paris }
          ports:
            - { name: http, containerPort: 8096 }
            - { name: https, containerPort: 8920 }
            - { name: discovery, protocol: UDP, containerPort: 7359 }
            - { name: dnla, protocol: UDP, containerPort: 1900 }
          volumeMounts:
            - name: data
              mountPath: /config
            - name: media
              mountPath: /data
              readOnly: true
          resources:
            requests: { cpu: 1000m, memory: 1Gi, gpu.intel.com/i915: 1 }
            limits: { cpu: 10000m, memory: 8Gi, gpu.intel.com/i915: 1 }

          # Its very fast to start, <10s
          readinessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 5
            periodSeconds: 2
            failureThreshold: 5
          livenessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 5
            failureThreshold: 5

      volumes:
        - name: data
          persistentVolumeClaim: { claimName: jellyfin-data-pvc }
        - name: media
          persistentVolumeClaim: { claimName: jellyfin-media-pvc }

      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
