---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: chart
spec:
  repo: https://traefik.github.io/charts
  chart: traefik
  version: v40.2.0
  targetNamespace: traefik
  createNamespace: true
  valuesContent: |-
    ingressClass:
      enabled: false
    providers:
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true

    ports:
      web:
        port: 80
        nodePort: 30000
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        port: 443
        nodePort: 30001
        http:
          middlewares:
            - traefik-limit-body-1g@kubernetescrd

    gateway:
      listeners:
        web:
          port: 80
          protocol: HTTP
          namespacePolicy:
            from: All
        websecure:
          port: 443
          protocol: HTTPS
          namespacePolicy:
            from: All
          mode: Terminate
          certificateRefs:
            - kind: Secret
              namespace: cert-manager
              name: mon-enorme-uk-tls
              group: ""

    logs:
      access:
        enabled: true
    metrics:
      prometheus:
        enabled: true
