---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy: { type: Recreate }

  template:
    spec:
      runtimeClassName: nvidia
      containers:
        - name: llama-server
          image: llama-server
          args:
            - --ui
            - --offline
            - --sleep-idle-seconds
            - '3600'
            - --threads-http
            - '2'
            - --models-max
            - '1'
            - --parallel
            - '-1'
            - --cache-ram
            - '8192'
            - --ctx-checkpoints
            - '5'
            - --direct-io
            - --models-dir
            - /models
            - --models-preset
            - /models/llama-server-model-presets.ini
            - --api-key-file
            - /var/run/secrets/enorme.uk/api-keys
          ports:
            - { name: http, containerPort: 8080 }
          volumeMounts:
            - name: models
              mountPath: /models
              readOnly: true
            - name: keys
              mountPath: /var/run/secrets/enorme.uk
              readOnly: true
          resources:
            requests: { cpu: 10m, memory: 10Gi, nvidia.com/gpu: 1 }
            limits: { cpu: 2000m, memory: 30Gi, nvidia.com/gpu: 1 }

      volumes:
        - name: models
          persistentVolumeClaim: { claimName: llama-models-pvc }
        - name: keys
          secret:
            secretName: llama-api-keys
            items:
              - { key: API_KEYS, path: api-keys }
