---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy: { type: Recreate }

  template:
    spec:
      runtimeClassName: nvidia
      containers:
        - name: llama-server
          image: llama-server
          args:
            - --sleep-idle-seconds
            - '3600'
            - --models-preset
            - /models/llama-server-model-presets.ini
          env:
            - { name: LLAMA_ARG_OFFLINE, value: 'true' }
            - { name: LLAMA_ARG_UI, value: 'true' }
            # - { name: LLAMA_ARG_ENDPOINT_METRICS, value: 'true' }

            - { name: LLAMA_ARG_MODELS_DIR, value: /models }

            - { name: LLAMA_ARG_THREADS_HTTP, value: '1' }
            - { name: LLAMA_ARG_MODELS_MAX, value: '1' }
            - { name: LLAMA_ARG_N_PARALLEL, value: '1' }
            - { name: LLAMA_ARG_CACHE_PROMPT, value: 'false' }

            - { name: LLAMA_ARG_API_KEY_FILE, value: /var/run/secrets/enorme.uk/api-keys }
          ports:
            - { name: http, containerPort: 8080 }
          volumeMounts:
            - name: models
              mountPath: /models
              readOnly: true
            - name: keys
              mountPath: /var/run/secrets/enorme.uk
              readOnly: true
          resources:
            requests: { cpu: 10m, memory: 128Mi, nvidia.com/gpu: 1 }
            limits: { cpu: 2000m, memory: 10Gi, nvidia.com/gpu: 1 }

      volumes:
        - name: models
          persistentVolumeClaim: { claimName: llama-models-pvc }
        - name: keys
          secret:
            secretName: llama-api-keys
            items:
              - { key: API_KEYS, path: api-keys }
