apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
spec:
  template:
    spec:
      containers:
        - name: intel-gpu-plugin
          args:
            # Default args
            - -enable-monitoring
            - -v=2
            # Allow the GPU to be shared by basically every container
            - -shared-dev-num=99
            # Deny the iGPU
            - -deny-ids=0x1912
